version: '3.8'
services:
  app:
    ports:
      - '8004:8004'
    environment:
      - BIG_SECRET=${BIG_SECRET}
      - BASE_URL=${BASE_URL}
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile